const routes = {
  LOGIN: 'Login',
  SPLASH: 'Splash',
  HOME: 'Home',
  TENDERS: 'Tenders',
  PROJECTS: 'Projects',
  TENDER_DETAILS: 'TENDER_DETAILS',
  PROJECT_DETAILS: 'PROJECT_DETAILS',
  SUBCONTRACTORS: 'SUBCONTRACTORS',
  QUANTITY_SUBMISSION: 'QUANTITY_SUBMISSION',
};

export default routes;