const constants = {
  SET_CONNECTION_STATUS: 'SET_CONNECTION_STATUS',
  SET_LOGGED_IN_USER: 'SET_LOGGED_IN_USER',
  APPROVE_TENDER: 'APPROVE_TENDER',
  DECLINE_TENDER: 'DECLINE_TENDER',
  ADD_TENDER_NOTE: 'ADD_TENDER_NOTE',
}

export default constants