const constants = {
  SET_CONNECTION_STATUS: 'SET_CONNECTION_STATUS',
  SET_LOGGED_IN_USER: 'SET_LOGGED_IN_USER',
  APPROVE_TENDER: 'APPROVE_TENDER',
  DECLINE_TENDER: 'DECLINE_TENDER',
  ADD_TENDER_NOTE: 'ADD_TENDER_NOTE',
  SET_TENDERS: 'SET_TENDERS',
  SET_PROJECTS: 'SET_PROJECTS',
  SET_AREA_MANAGERS: 'SET_AREA_MANAGERS',
  SET_QUANTITY_SUBMISSIONS: 'SET_QUANTITY_SUBMISSIONS',
}

export default constants